# Generated by Django 4.1 on 2022-09-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regional_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('regional_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('constituency_name', models.CharField(max_length=500)),
                ('counted', models.BooleanField(default=False)),
                ('regional_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constituency.region')),
            ],
        ),
    ]
