# Generated by Django 4.1 on 2022-09-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constituency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_vote', models.CharField(max_length=50)),
                ('npp_vote', models.CharField(max_length=50)),
                ('other_vote', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constituency.constituency')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constituency.region')),
            ],
        ),
    ]
